### ISSUE TITLE
License causes an error

### ISSUE THREAD

**Issue by jmontleon** [spacemit-com/linux-k1x#2]
https://github.com/spacemit-com/linux-k1x/blob/f87dd5a168fda32c69c26faf5a8b6da46511fab0/drivers/watchdog/k1x_wdt.c#L848

`GPL-incompatible module k1x_wdt.ko uses GPL-only symbol`

The license should be `GPL v2`, not `GPL-v2`.

**Comment by kevin-zhm** [comment]
Fix done.
