### ISSUE TITLE
dw-axi-dmac-platform.c fails to compile

### ISSUE THREAD

**Issue by jmontleon** [spacemit-com/linux-k1x#5]
https://github.com/spacemit-com/linux-k1x/blob/f87dd5a168fda32c69c26faf5a8b6da46511fab0/drivers/dma/dw-axi-dmac/dw-axi-dmac-platform.c#L1693

Should this be `AXI_DMA_FLAG_HAS_RESETS,`?

**Comment by kevin-zhm** [comment]
Fix done
